name: CI
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v1"
      with:
        fail_ci_if_error: true
    - uses: actions/upload-artifact@v2
      with:
        name: tests
        path: target/test-reports/**
    #- uses: actions/checkout@v2
    #- name: Formatting
    #  run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

