name: CI
on:
  pull_request:
    branches:
      - master
      - feature/**
  push:
    branches:
      - master
      - feature/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test -Dfile.encoding=UTF-8
      - name: Checking the code with scalafmt
        uses: AvaPL/scalafmt-native-formatter@v0
        with:
          conf-path: ./.scalafmt.conf

