name: CI
on:
  pull_request:
    branches:
      - master
      - feature/**
  push:
    branches:
      - master
      - feature/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt coverage test -Dfile.encoding=UTF-8
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

